pr:
  autoCancel: false
  branches:
    include:
    - '*'

pool:
  vmImage: 'windows-2022'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'snesterov-wif-manual'
    scriptType: 'batch'
    scriptLocation: 'inlineScript'
    inlineScript: 'az account show'