#!/bin/sh

set -e

SCRIPT=$0
SCRIPT_DIR=$(cd $(dirname "$SCRIPT") && pwd)

dotnet restore
dotnet run -p $SCRIPT_DIR/projects/client/Apigen --apiName:AMQP_0_9_1 $SCRIPT_DIR/docs/specs/amqp0-9-1.stripped.xml $SCRIPT_DIR/gensrc/autogenerated-api-0-9-1.cs
dotnet build $SCRIPT_DIR/projects/client/RabbitMQ.Client
dotnet build $SCRIPT_DIR/projects/client/Unit
