#! /bin/sh

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=pyle.cgi
NAME=pyle2
DESC=pyle2

test -x $DAEMON || exit 0

set -e

start_pyle2 () {
    $DAEMON >> /var/log/$NAME 2>&1 &
    echo $! > /var/run/$NAME.pid
}

stop_pyle2 () {
    kill $(cat /var/run/$NAME.pid)
}

case "$1" in
  start)
	echo -n "Starting $DESC: "
	start_pyle2
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	stop_pyle2
	echo "$NAME."
	;;
  restart)
	echo -n "Restarting $DESC: "
	stop_pyle2
	sleep 1
	start_pyle2
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0
