// Autogenerated code. Do not edit.

// This source code is dual-licensed under the Apache License, version
// 2.0, and the Mozilla Public License, version 1.1.
//
// The APL v2.0:
//
//---------------------------------------------------------------------------
//   Copyright (c) 2007-2020 VMware, Inc.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       https://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//---------------------------------------------------------------------------
//
// The MPL v1.1:
//
//---------------------------------------------------------------------------
//   The contents of this file are subject to the Mozilla Public License
//   Version 1.1 (the "License"); you may not use this file except in
//   compliance with the License. You may obtain a copy of the License at
//   https://www.rabbitmq.com/mpl.html
//
//   Software distributed under the License is distributed on an "AS IS"
//   basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
//   License for the specific language governing rights and limitations
//   under the License.
//
//   The Original Code is RabbitMQ.
//
//   The Initial Developer of the Original Code is Pivotal Software, Inc.
//   Copyright (c) 2007-2020 VMware, Inc.  All rights reserved.
//---------------------------------------------------------------------------

using System.Text;
namespace RabbitMQ.Client.Framing.Impl
{
    /// <summary>Autogenerated type. Private implementation class - do not use directly.</summary>
    internal sealed class BasicPublish : Client.Impl.MethodBase, IBasicPublish
    {

        public ushort _reserved1;
        public string _exchange;
        public string _routingKey;
        public bool _mandatory;
        public bool _immediate;

        ushort IBasicPublish.Reserved1 => _reserved1;
        string IBasicPublish.Exchange => _exchange;
        string IBasicPublish.RoutingKey => _routingKey;
        bool IBasicPublish.Mandatory => _mandatory;
        bool IBasicPublish.Immediate => _immediate;

        public BasicPublish() { }
        public BasicPublish(ushort @Reserved1, string @Exchange, string @RoutingKey, bool @Mandatory, bool @Immediate)
        {
            _reserved1 = @Reserved1;
            _exchange = @Exchange;
            _routingKey = @RoutingKey;
            _mandatory = @Mandatory;
            _immediate = @Immediate;
        }

        public override uint ProtocolCommandId => MethodConstants.BasicPublish;
        public override string ProtocolMethodName => "basic.publish";
        public override bool HasContent => true;

        public override void ReadArgumentsFrom(ref Client.Impl.MethodArgumentReader reader)
        {
            _reserved1 = reader.ReadShort();
            _exchange = reader.ReadShortstr();
            _routingKey = reader.ReadShortstr();
            _mandatory = reader.ReadBit();
            _immediate = reader.ReadBit();
        }

        public override void WriteArgumentsTo(ref Client.Impl.MethodArgumentWriter writer)
        {
            writer.WriteShort(_reserved1);
            writer.WriteShortstr(_exchange);
            writer.WriteShortstr(_routingKey);
            writer.WriteBit(_mandatory);
            writer.WriteBit(_immediate);
        }

        public override int GetRequiredBufferSize()
        {
            int bufferSize = 0;
            bufferSize += 2; // _reserved1 in bytes
            bufferSize += 1 + Encoding.UTF8.GetByteCount(_exchange); // _exchange in bytes
            bufferSize += 1 + Encoding.UTF8.GetByteCount(_routingKey); // _routingKey in bytes
            bufferSize += 1; // number of bit fields in bytes
            return bufferSize;
        }

        public override void AppendArgumentDebugStringTo(StringBuilder sb)
        {
            sb.Append("(");
            sb.Append(_reserved1); sb.Append(",");
            sb.Append(_exchange); sb.Append(",");
            sb.Append(_routingKey); sb.Append(",");
            sb.Append(_mandatory); sb.Append(",");
            sb.Append(_immediate);
            sb.Append(")");
        }
    }
}
