// Autogenerated code. Do not edit.

// This source code is dual-licensed under the Apache License, version
// 2.0, and the Mozilla Public License, version 1.1.
//
// The APL v2.0:
//
//---------------------------------------------------------------------------
//   Copyright (c) 2007-2020 VMware, Inc.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       https://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//---------------------------------------------------------------------------
//
// The MPL v1.1:
//
//---------------------------------------------------------------------------
//   The contents of this file are subject to the Mozilla Public License
//   Version 1.1 (the "License"); you may not use this file except in
//   compliance with the License. You may obtain a copy of the License at
//   https://www.rabbitmq.com/mpl.html
//
//   Software distributed under the License is distributed on an "AS IS"
//   basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
//   License for the specific language governing rights and limitations
//   under the License.
//
//   The Original Code is RabbitMQ.
//
//   The Initial Developer of the Original Code is Pivotal Software, Inc.
//   Copyright (c) 2007-2020 VMware, Inc.  All rights reserved.
//---------------------------------------------------------------------------

using System.Text;
namespace RabbitMQ.Client.Framing.Impl
{
    /// <summary>Autogenerated type. Private implementation class - do not use directly.</summary>
    internal sealed class BasicDeliver : Client.Impl.MethodBase, IBasicDeliver
    {

        public string _consumerTag;
        public ulong _deliveryTag;
        public bool _redelivered;
        public string _exchange;
        public string _routingKey;

        string IBasicDeliver.ConsumerTag => _consumerTag;
        ulong IBasicDeliver.DeliveryTag => _deliveryTag;
        bool IBasicDeliver.Redelivered => _redelivered;
        string IBasicDeliver.Exchange => _exchange;
        string IBasicDeliver.RoutingKey => _routingKey;

        public BasicDeliver() { }
        public BasicDeliver(string @ConsumerTag, ulong @DeliveryTag, bool @Redelivered, string @Exchange, string @RoutingKey)
        {
            _consumerTag = @ConsumerTag;
            _deliveryTag = @DeliveryTag;
            _redelivered = @Redelivered;
            _exchange = @Exchange;
            _routingKey = @RoutingKey;
        }

        public override uint ProtocolCommandId => MethodConstants.BasicDeliver;
        public override string ProtocolMethodName => "basic.deliver";
        public override bool HasContent => true;

        public override void ReadArgumentsFrom(ref Client.Impl.MethodArgumentReader reader)
        {
            _consumerTag = reader.ReadShortstr();
            _deliveryTag = reader.ReadLonglong();
            _redelivered = reader.ReadBit();
            _exchange = reader.ReadShortstr();
            _routingKey = reader.ReadShortstr();
        }

        public override void WriteArgumentsTo(ref Client.Impl.MethodArgumentWriter writer)
        {
            writer.WriteShortstr(_consumerTag);
            writer.WriteLonglong(_deliveryTag);
            writer.WriteBit(_redelivered);
            writer.WriteShortstr(_exchange);
            writer.WriteShortstr(_routingKey);
        }

        public override int GetRequiredBufferSize()
        {
            int bufferSize = 0;
            bufferSize += 1 + Encoding.UTF8.GetByteCount(_consumerTag); // _consumerTag in bytes
            bufferSize += 8; // _deliveryTag in bytes
            bufferSize += 1 + Encoding.UTF8.GetByteCount(_exchange); // _exchange in bytes
            bufferSize += 1 + Encoding.UTF8.GetByteCount(_routingKey); // _routingKey in bytes
            bufferSize += 1; // number of bit fields in bytes
            return bufferSize;
        }

        public override void AppendArgumentDebugStringTo(StringBuilder sb)
        {
            sb.Append("(");
            sb.Append(_consumerTag); sb.Append(",");
            sb.Append(_deliveryTag); sb.Append(",");
            sb.Append(_redelivered); sb.Append(",");
            sb.Append(_exchange); sb.Append(",");
            sb.Append(_routingKey);
            sb.Append(")");
        }
    }
}
