// Autogenerated code. Do not edit.

// This source code is dual-licensed under the Apache License, version
// 2.0, and the Mozilla Public License, version 1.1.
//
// The APL v2.0:
//
//---------------------------------------------------------------------------
//   Copyright (c) 2007-2020 VMware, Inc.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       https://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//---------------------------------------------------------------------------
//
// The MPL v1.1:
//
//---------------------------------------------------------------------------
//   The contents of this file are subject to the Mozilla Public License
//   Version 1.1 (the "License"); you may not use this file except in
//   compliance with the License. You may obtain a copy of the License at
//   https://www.rabbitmq.com/mpl.html
//
//   Software distributed under the License is distributed on an "AS IS"
//   basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
//   License for the specific language governing rights and limitations
//   under the License.
//
//   The Original Code is RabbitMQ.
//
//   The Initial Developer of the Original Code is Pivotal Software, Inc.
//   Copyright (c) 2007-2020 VMware, Inc.  All rights reserved.
//---------------------------------------------------------------------------

using System.Text;
namespace RabbitMQ.Client.Framing.Impl
{
    /// <summary>Autogenerated type. Private implementation class - do not use directly.</summary>
    internal sealed class ConnectionClose : Client.Impl.MethodBase, IConnectionClose
    {

        public ushort _replyCode;
        public string _replyText;
        public ushort _classId;
        public ushort _methodId;

        ushort IConnectionClose.ReplyCode => _replyCode;
        string IConnectionClose.ReplyText => _replyText;
        ushort IConnectionClose.ClassId => _classId;
        ushort IConnectionClose.MethodId => _methodId;

        public ConnectionClose() { }
        public ConnectionClose(ushort @ReplyCode, string @ReplyText, ushort @ClassId, ushort @MethodId)
        {
            _replyCode = @ReplyCode;
            _replyText = @ReplyText;
            _classId = @ClassId;
            _methodId = @MethodId;
        }

        public override uint ProtocolCommandId => MethodConstants.ConnectionClose;
        public override string ProtocolMethodName => "connection.close";
        public override bool HasContent => false;

        public override void ReadArgumentsFrom(ref Client.Impl.MethodArgumentReader reader)
        {
            _replyCode = reader.ReadShort();
            _replyText = reader.ReadShortstr();
            _classId = reader.ReadShort();
            _methodId = reader.ReadShort();
        }

        public override void WriteArgumentsTo(ref Client.Impl.MethodArgumentWriter writer)
        {
            writer.WriteShort(_replyCode);
            writer.WriteShortstr(_replyText);
            writer.WriteShort(_classId);
            writer.WriteShort(_methodId);
        }

        public override int GetRequiredBufferSize()
        {
            int bufferSize = 0;
            bufferSize += 2; // _replyCode in bytes
            bufferSize += 1 + Encoding.UTF8.GetByteCount(_replyText); // _replyText in bytes
            bufferSize += 2; // _classId in bytes
            bufferSize += 2; // _methodId in bytes
            return bufferSize;
        }

        public override void AppendArgumentDebugStringTo(StringBuilder sb)
        {
            sb.Append("(");
            sb.Append(_replyCode); sb.Append(",");
            sb.Append(_replyText); sb.Append(",");
            sb.Append(_classId); sb.Append(",");
            sb.Append(_methodId);
            sb.Append(")");
        }
    }
}
