// This source code is dual-licensed under the Apache License, version
// 2.0, and the Mozilla Public License, version 2.0.
//
// The APL v2.0:
//
//---------------------------------------------------------------------------
//   Copyright (c) 2007-2020 VMware, Inc.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       https://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//---------------------------------------------------------------------------
//
// The MPL v2.0:
//
//---------------------------------------------------------------------------
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
//  Copyright (c) 2007-2020 VMware, Inc.  All rights reserved.
//---------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using RabbitMQ.Client.Impl;

namespace RabbitMQ.Client.Framing
{
    /// <summary>Autogenerated type. AMQP specification content header properties for content class "basic"</summary>
    internal sealed class BasicProperties : RabbitMQ.Client.Impl.BasicProperties
    {
        private string _contentType;
        private string _contentEncoding;
        private IDictionary<string, object> _headers;
        private byte _deliveryMode;
        private byte _priority;
        private string _correlationId;
        private string _replyTo;
        private string _expiration;
        private string _messageId;
        private AmqpTimestamp _timestamp;
        private string _type;
        private string _userId;
        private string _appId;
        private string _clusterId;

        public override string ContentType
        {
            get => _contentType;
            set => _contentType = value;
        }

        public override string ContentEncoding
        {
            get => _contentEncoding;
            set => _contentEncoding = value;
        }

        public override IDictionary<string, object> Headers
        {
            get => _headers;
            set => _headers = value;
        }

        public override byte DeliveryMode
        {
            get => _deliveryMode;
            set => _deliveryMode = value;
        }

        public override byte Priority
        {
            get => _priority;
            set => _priority = value;
        }

        public override string CorrelationId
        {
            get => _correlationId;
            set => _correlationId = value;
        }

        public override string ReplyTo
        {
            get => _replyTo;
            set => _replyTo = value;
        }

        public override string Expiration
        {
            get => _expiration;
            set => _expiration = value;
        }

        public override string MessageId
        {
            get => _messageId;
            set => _messageId = value;
        }

        public override AmqpTimestamp Timestamp
        {
            get => _timestamp;
            set => _timestamp = value;
        }

        public override string Type
        {
            get => _type;
            set => _type = value;
        }

        public override string UserId
        {
            get => _userId;
            set => _userId = value;
        }

        public override string AppId
        {
            get => _appId;
            set => _appId = value;
        }

        public override string ClusterId
        {
            get => _clusterId;
            set => _clusterId = value;
        }

        public override void ClearContentType() => _contentType = default;

        public override void ClearContentEncoding() => _contentEncoding = default;

        public override void ClearHeaders() => _headers = default;

        public override void ClearDeliveryMode() => _deliveryMode = default;

        public override void ClearPriority() => _priority = default;

        public override void ClearCorrelationId() => _correlationId = default;

        public override void ClearReplyTo() => _replyTo = default;

        public override void ClearExpiration() => _expiration = default;

        public override void ClearMessageId() => _messageId = default;

        public override void ClearTimestamp() => _timestamp = default;

        public override void ClearType() => _type = default;

        public override void ClearUserId() => _userId = default;

        public override void ClearAppId() => _appId = default;

        public override void ClearClusterId() => _clusterId = default;

        public override bool IsContentTypePresent() => _contentType != default;

        public override bool IsContentEncodingPresent() => _contentEncoding != default;

        public override bool IsHeadersPresent() => _headers != default;

        public override bool IsDeliveryModePresent() => _deliveryMode != default;

        public override bool IsPriorityPresent() => _priority != default;

        public override bool IsCorrelationIdPresent() => _correlationId != default;

        public override bool IsReplyToPresent() => _replyTo != default;

        public override bool IsExpirationPresent() => _expiration != default;

        public override bool IsMessageIdPresent() => _messageId != default;

        public override bool IsTimestampPresent() => _timestamp != default;

        public override bool IsTypePresent() => _type != default;

        public override bool IsUserIdPresent() => _userId != default;

        public override bool IsAppIdPresent() => _appId != default;

        public override bool IsClusterIdPresent() => _clusterId != default;

        public BasicProperties()
        {
        }

        public BasicProperties(ReadOnlySpan<byte> span)
        {
            int offset = 2;
            ref readonly byte bits = ref span[0];
            if (bits.IsBitSet(ContentTypeBit)) { offset += WireFormatting.ReadShortstr(span.Slice(offset), out _contentType); }
            if (bits.IsBitSet(ContentEncodingBit)) { offset += WireFormatting.ReadShortstr(span.Slice(offset), out _contentEncoding); }
            if (bits.IsBitSet(HeaderBit)) { offset += WireFormatting.ReadDictionary(span.Slice(offset), out var tmpDirectory); _headers = tmpDirectory; }
            if (bits.IsBitSet(DeliveryModeBit)) { _deliveryMode = span[offset++]; }
            if (bits.IsBitSet(PriorityBit)) { _priority = span[offset++]; }
            if (bits.IsBitSet(CorrelationIdBit)) { offset += WireFormatting.ReadShortstr(span.Slice(offset), out _correlationId); }
            if (bits.IsBitSet(ReplyToBit)) { offset += WireFormatting.ReadShortstr(span.Slice(offset), out _replyTo); }
            if (bits.IsBitSet(ExpirationBit)) { offset += WireFormatting.ReadShortstr(span.Slice(offset), out _expiration); }

            bits = ref span[1];
            if (bits.IsBitSet(MessageIdBit)) { offset += WireFormatting.ReadShortstr(span.Slice(offset), out _messageId); }
            if (bits.IsBitSet(TimestampBit)) { offset += WireFormatting.ReadTimestamp(span.Slice(offset), out _timestamp); }
            if (bits.IsBitSet(TypeBit)) { offset += WireFormatting.ReadShortstr(span.Slice(offset), out _type); }
            if (bits.IsBitSet(UserIdBit)) { offset += WireFormatting.ReadShortstr(span.Slice(offset), out _userId); }
            if (bits.IsBitSet(AppIdBit)) { offset += WireFormatting.ReadShortstr(span.Slice(offset), out _appId); }
            if (bits.IsBitSet(ClusterIdBit)) { WireFormatting.ReadShortstr(span.Slice(offset), out _clusterId); }
        }

        public override ushort ProtocolClassId => 60;
        public override string ProtocolClassName => "basic";

        //----------------------------------
        // First byte
        //----------------------------------
        private const byte ContentTypeBit = 7;
        private const byte ContentEncodingBit = 6;
        private const byte HeaderBit = 5;
        private const byte DeliveryModeBit = 4;
        private const byte PriorityBit = 3;
        private const byte CorrelationIdBit = 2;
        private const byte ReplyToBit = 1;
        private const byte ExpirationBit = 0;

        //----------------------------------
        // Second byte
        //----------------------------------
        private const byte MessageIdBit = 7;
        private const byte TimestampBit = 6;
        private const byte TypeBit = 5;
        private const byte UserIdBit = 4;
        private const byte AppIdBit = 3;
        private const byte ClusterIdBit = 2;

        internal override int WritePropertiesTo(Span<byte> span)
        {
            int offset = 2;
            ref byte bitValue = ref span.GetStart();
            bitValue = 0;
            if (IsContentTypePresent())
            {
                bitValue.SetBit(ContentTypeBit);
                offset += WireFormatting.WriteShortstr(ref span.GetOffset(offset), _contentType);
            }

            if (IsContentEncodingPresent())
            {
                bitValue.SetBit(ContentEncodingBit);
                offset += WireFormatting.WriteShortstr(ref span.GetOffset(offset), _contentEncoding);
            }

            if (IsHeadersPresent())
            {
                bitValue.SetBit(HeaderBit);
                offset += WireFormatting.WriteTable(ref span.GetOffset(offset), _headers);
            }

            if (IsDeliveryModePresent())
            {
                bitValue.SetBit(DeliveryModeBit);
                span.GetOffset(offset++) = _deliveryMode;
            }

            if (IsPriorityPresent())
            {
                bitValue.SetBit(PriorityBit);
                span.GetOffset(offset++) = _priority;
            }

            if (IsCorrelationIdPresent())
            {
                bitValue.SetBit(CorrelationIdBit);
                offset += WireFormatting.WriteShortstr(ref span.GetOffset(offset), _correlationId);
            }

            if (IsReplyToPresent())
            {
                bitValue.SetBit(ReplyToBit);
                offset += WireFormatting.WriteShortstr(ref span.GetOffset(offset), _replyTo);
            }

            if (IsExpirationPresent())
            {
                bitValue.SetBit(ExpirationBit);
                offset += WireFormatting.WriteShortstr(ref span.GetOffset(offset), _expiration);
            }

            bitValue = ref span.GetOffset(1);
            bitValue = 0;
            if (IsMessageIdPresent())
            {
                bitValue.SetBit(MessageIdBit);
                offset += WireFormatting.WriteShortstr(ref span.GetOffset(offset), _messageId);
            }

            if (IsTimestampPresent())
            {
                bitValue.SetBit(TimestampBit);
                offset += WireFormatting.WriteTimestamp(ref span.GetOffset(offset), _timestamp);
            }

            if (IsTypePresent())
            {
                bitValue.SetBit(TypeBit);
                offset += WireFormatting.WriteShortstr(ref span.GetOffset(offset), _type);
            }

            if (IsUserIdPresent())
            {
                bitValue.SetBit(UserIdBit);
                offset += WireFormatting.WriteShortstr(ref span.GetOffset(offset), _userId);
            }

            if (IsAppIdPresent())
            {
                bitValue.SetBit(AppIdBit);
                offset += WireFormatting.WriteShortstr(ref span.GetOffset(offset), _appId);
            }

            if (IsClusterIdPresent())
            {
                bitValue.SetBit(ClusterIdBit);
                offset += WireFormatting.WriteShortstr(ref span.GetOffset(offset), _clusterId);
            }

            return offset;
        }

        public override int GetRequiredPayloadBufferSize()
        {
            int bufferSize = 2; // number of presence fields (14) in 2 bytes blocks
            if (IsContentTypePresent()) { bufferSize += 1 + WireFormatting.GetByteCount(_contentType); } // _contentType in bytes
            if (IsContentEncodingPresent()) { bufferSize += 1 + WireFormatting.GetByteCount(_contentEncoding); } // _contentEncoding in bytes
            if (IsHeadersPresent()) { bufferSize += WireFormatting.GetTableByteCount(_headers); } // _headers in bytes
            if (IsDeliveryModePresent()) { bufferSize++; } // _deliveryMode in bytes
            if (IsPriorityPresent()) { bufferSize++; } // _priority in bytes
            if (IsCorrelationIdPresent()) { bufferSize += 1 + WireFormatting.GetByteCount(_correlationId); } // _correlationId in bytes
            if (IsReplyToPresent()) { bufferSize += 1 + WireFormatting.GetByteCount(_replyTo); } // _replyTo in bytes
            if (IsExpirationPresent()) { bufferSize += 1 + WireFormatting.GetByteCount(_expiration); } // _expiration in bytes
            if (IsMessageIdPresent()) { bufferSize += 1 + WireFormatting.GetByteCount(_messageId); } // _messageId in bytes
            if (IsTimestampPresent()) { bufferSize += 8; } // _timestamp in bytes
            if (IsTypePresent()) { bufferSize += 1 + WireFormatting.GetByteCount(_type); } // _type in bytes
            if (IsUserIdPresent()) { bufferSize += 1 + WireFormatting.GetByteCount(_userId); } // _userId in bytes
            if (IsAppIdPresent()) { bufferSize += 1 + WireFormatting.GetByteCount(_appId); } // _appId in bytes
            if (IsClusterIdPresent()) { bufferSize += 1 + WireFormatting.GetByteCount(_clusterId); } // _clusterId in bytes
            return bufferSize;
        }
    }
}
