// This source code is dual-licensed under the Apache License, version
// 2.0, and the Mozilla Public License, version 2.0.
//
// The APL v2.0:
//
//---------------------------------------------------------------------------
//   Copyright (c) 2007-2020 VMware, Inc.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       https://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//---------------------------------------------------------------------------
//
// The MPL v2.0:
//
//---------------------------------------------------------------------------
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
//  Copyright (c) 2007-2020 VMware, Inc.  All rights reserved.
//---------------------------------------------------------------------------

using System.Collections.Generic;
using System.Text;
using RabbitMQ.Client.Impl;

namespace RabbitMQ.Client.Framing
{
    /// <summary>Autogenerated type. AMQP specification content header properties for content class "basic"</summary>
    internal sealed class BasicProperties : RabbitMQ.Client.Impl.BasicProperties
    {
        private string _contentType;
        private string _contentEncoding;
        private IDictionary<string, object> _headers;
        private byte _deliveryMode;
        private byte _priority;
        private string _correlationId;
        private string _replyTo;
        private string _expiration;
        private string _messageId;
        private AmqpTimestamp _timestamp;
        private string _type;
        private string _userId;
        private string _appId;
        private string _clusterId;

        public override string ContentType
        {
            get => _contentType;
            set => _contentType = value;
        }

        public override string ContentEncoding
        {
            get => _contentEncoding;
            set => _contentEncoding = value;
        }

        public override IDictionary<string, object> Headers
        {
            get => _headers;
            set => _headers = value;
        }

        public override byte DeliveryMode
        {
            get => _deliveryMode;
            set => _deliveryMode = value;
        }

        public override byte Priority
        {
            get => _priority;
            set => _priority = value;
        }

        public override string CorrelationId
        {
            get => _correlationId;
            set => _correlationId = value;
        }

        public override string ReplyTo
        {
            get => _replyTo;
            set => _replyTo = value;
        }

        public override string Expiration
        {
            get => _expiration;
            set => _expiration = value;
        }

        public override string MessageId
        {
            get => _messageId;
            set => _messageId = value;
        }

        public override AmqpTimestamp Timestamp
        {
            get => _timestamp;
            set => _timestamp = value;
        }

        public override string Type
        {
            get => _type;
            set => _type = value;
        }

        public override string UserId
        {
            get => _userId;
            set => _userId = value;
        }

        public override string AppId
        {
            get => _appId;
            set => _appId = value;
        }

        public override string ClusterId
        {
            get => _clusterId;
            set => _clusterId = value;
        }

        public override void ClearContentType() => _contentType = default;

        public override void ClearContentEncoding() => _contentEncoding = default;

        public override void ClearHeaders() => _headers = default;

        public override void ClearDeliveryMode() => _deliveryMode = default;

        public override void ClearPriority() => _priority = default;

        public override void ClearCorrelationId() => _correlationId = default;

        public override void ClearReplyTo() => _replyTo = default;

        public override void ClearExpiration() => _expiration = default;

        public override void ClearMessageId() => _messageId = default;

        public override void ClearTimestamp() => _timestamp = default;

        public override void ClearType() => _type = default;

        public override void ClearUserId() => _userId = default;

        public override void ClearAppId() => _appId = default;

        public override void ClearClusterId() => _clusterId = default;

        public override bool IsContentTypePresent() => _contentType != default;

        public override bool IsContentEncodingPresent() => _contentEncoding != default;

        public override bool IsHeadersPresent() => _headers != default;

        public override bool IsDeliveryModePresent() => _deliveryMode != default;

        public override bool IsPriorityPresent() => _priority != default;

        public override bool IsCorrelationIdPresent() => _correlationId != default;

        public override bool IsReplyToPresent() => _replyTo != default;

        public override bool IsExpirationPresent() => _expiration != default;

        public override bool IsMessageIdPresent() => _messageId != default;

        public override bool IsTimestampPresent() => _timestamp != default;

        public override bool IsTypePresent() => _type != default;

        public override bool IsUserIdPresent() => _userId != default;

        public override bool IsAppIdPresent() => _appId != default;

        public override bool IsClusterIdPresent() => _clusterId != default;

        public BasicProperties()
        {
        }

        public override ushort ProtocolClassId => 60;
        public override string ProtocolClassName => "basic";

        internal override void ReadPropertiesFrom(ref ContentHeaderPropertyReader reader)
        {
            bool contentType_present = reader.ReadPresence();
            bool contentEncoding_present = reader.ReadPresence();
            bool headers_present = reader.ReadPresence();
            bool deliveryMode_present = reader.ReadPresence();
            bool priority_present = reader.ReadPresence();
            bool correlationId_present = reader.ReadPresence();
            bool replyTo_present = reader.ReadPresence();
            bool expiration_present = reader.ReadPresence();
            bool messageId_present = reader.ReadPresence();
            bool timestamp_present = reader.ReadPresence();
            bool type_present = reader.ReadPresence();
            bool userId_present = reader.ReadPresence();
            bool appId_present = reader.ReadPresence();
            bool clusterId_present = reader.ReadPresence();
            reader.FinishPresence();
            if (contentType_present) { _contentType = reader.ReadShortstr(); }
            if (contentEncoding_present) { _contentEncoding = reader.ReadShortstr(); }
            if (headers_present) { _headers = reader.ReadTable(); }
            if (deliveryMode_present) { _deliveryMode = reader.ReadOctet(); }
            if (priority_present) { _priority = reader.ReadOctet(); }
            if (correlationId_present) { _correlationId = reader.ReadShortstr(); }
            if (replyTo_present) { _replyTo = reader.ReadShortstr(); }
            if (expiration_present) { _expiration = reader.ReadShortstr(); }
            if (messageId_present) { _messageId = reader.ReadShortstr(); }
            if (timestamp_present) { _timestamp = reader.ReadTimestamp(); }
            if (type_present) { _type = reader.ReadShortstr(); }
            if (userId_present) { _userId = reader.ReadShortstr(); }
            if (appId_present) { _appId = reader.ReadShortstr(); }
            if (clusterId_present) { _clusterId = reader.ReadShortstr(); }
        }

        internal override void WritePropertiesTo(ref ContentHeaderPropertyWriter writer)
        {
            writer.WritePresence(IsContentTypePresent());
            writer.WritePresence(IsContentEncodingPresent());
            writer.WritePresence(IsHeadersPresent());
            writer.WritePresence(IsDeliveryModePresent());
            writer.WritePresence(IsPriorityPresent());
            writer.WritePresence(IsCorrelationIdPresent());
            writer.WritePresence(IsReplyToPresent());
            writer.WritePresence(IsExpirationPresent());
            writer.WritePresence(IsMessageIdPresent());
            writer.WritePresence(IsTimestampPresent());
            writer.WritePresence(IsTypePresent());
            writer.WritePresence(IsUserIdPresent());
            writer.WritePresence(IsAppIdPresent());
            writer.WritePresence(IsClusterIdPresent());
            writer.FinishPresence();
            if (IsContentTypePresent()) { writer.WriteShortstr(_contentType); }
            if (IsContentEncodingPresent()) { writer.WriteShortstr(_contentEncoding); }
            if (IsHeadersPresent()) { writer.WriteTable(_headers); }
            if (IsDeliveryModePresent()) { writer.WriteOctet(_deliveryMode); }
            if (IsPriorityPresent()) { writer.WriteOctet(_priority); }
            if (IsCorrelationIdPresent()) { writer.WriteShortstr(_correlationId); }
            if (IsReplyToPresent()) { writer.WriteShortstr(_replyTo); }
            if (IsExpirationPresent()) { writer.WriteShortstr(_expiration); }
            if (IsMessageIdPresent()) { writer.WriteShortstr(_messageId); }
            if (IsTimestampPresent()) { writer.WriteTimestamp(_timestamp); }
            if (IsTypePresent()) { writer.WriteShortstr(_type); }
            if (IsUserIdPresent()) { writer.WriteShortstr(_userId); }
            if (IsAppIdPresent()) { writer.WriteShortstr(_appId); }
            if (IsClusterIdPresent()) { writer.WriteShortstr(_clusterId); }
        }

        public override int GetRequiredPayloadBufferSize()
        {
            int bufferSize = 2; // number of presence fields (14) in 2 bytes blocks
            if (IsContentTypePresent()) { bufferSize += 1 + Encoding.UTF8.GetByteCount(_contentType); } // _contentType in bytes
            if (IsContentEncodingPresent()) { bufferSize += 1 + Encoding.UTF8.GetByteCount(_contentEncoding); } // _contentEncoding in bytes
            if (IsHeadersPresent()) { bufferSize += WireFormatting.GetTableByteCount(_headers); } // _headers in bytes
            if (IsDeliveryModePresent()) { bufferSize++; } // _deliveryMode in bytes
            if (IsPriorityPresent()) { bufferSize++; } // _priority in bytes
            if (IsCorrelationIdPresent()) { bufferSize += 1 + Encoding.UTF8.GetByteCount(_correlationId); } // _correlationId in bytes
            if (IsReplyToPresent()) { bufferSize += 1 + Encoding.UTF8.GetByteCount(_replyTo); } // _replyTo in bytes
            if (IsExpirationPresent()) { bufferSize += 1 + Encoding.UTF8.GetByteCount(_expiration); } // _expiration in bytes
            if (IsMessageIdPresent()) { bufferSize += 1 + Encoding.UTF8.GetByteCount(_messageId); } // _messageId in bytes
            if (IsTimestampPresent()) { bufferSize += 8; } // _timestamp in bytes
            if (IsTypePresent()) { bufferSize += 1 + Encoding.UTF8.GetByteCount(_type); } // _type in bytes
            if (IsUserIdPresent()) { bufferSize += 1 + Encoding.UTF8.GetByteCount(_userId); } // _userId in bytes
            if (IsAppIdPresent()) { bufferSize += 1 + Encoding.UTF8.GetByteCount(_appId); } // _appId in bytes
            if (IsClusterIdPresent()) { bufferSize += 1 + Encoding.UTF8.GetByteCount(_clusterId); } // _clusterId in bytes
            return bufferSize;
        }
    }
}
