// This source code is dual-licensed under the Apache License, version
// 2.0, and the Mozilla Public License, version 2.0.
//
// The APL v2.0:
//
//---------------------------------------------------------------------------
//   Copyright (c) 2007-2020 VMware, Inc.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       https://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//---------------------------------------------------------------------------
//
// The MPL v2.0:
//
//---------------------------------------------------------------------------
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
//  Copyright (c) 2007-2020 VMware, Inc.  All rights reserved.
//---------------------------------------------------------------------------

using System.Collections.Generic;
using System.Text;
using RabbitMQ.Client.Impl;

namespace RabbitMQ.Client.Framing.Impl
{
    /// <summary>Autogenerated type. Private implementation class - do not use directly.</summary>
    internal sealed class ExchangeDeclare : Client.Impl.MethodBase
    {
        public ushort _reserved1;
        public string _exchange;
        public string _type;
        public bool _passive;
        public bool _durable;
        public bool _autoDelete;
        public bool _internal;
        public bool _nowait;
        public IDictionary<string, object> _arguments;

        ushort Reserved1 => _reserved1;
        string Exchange => _exchange;
        string Type => _type;
        bool Passive => _passive;
        bool Durable => _durable;
        bool AutoDelete => _autoDelete;
        bool Internal => _internal;
        bool Nowait => _nowait;
        IDictionary<string, object> Arguments => _arguments;

        public ExchangeDeclare() {}
        public ExchangeDeclare(ushort @Reserved1, string @Exchange, string @Type, bool @Passive, bool @Durable, bool @AutoDelete, bool @Internal, bool @Nowait, IDictionary<string, object> @Arguments)
        {
            _reserved1 = @Reserved1;
            _exchange = @Exchange;
            _type = @Type;
            _passive = @Passive;
            _durable = @Durable;
            _autoDelete = @AutoDelete;
            _internal = @Internal;
            _nowait = @Nowait;
            _arguments = @Arguments;
        }

        public override ushort ProtocolClassId => ClassConstants.Exchange;
        public override ushort ProtocolMethodId => ExchangeMethodConstants.Declare;
        public override string ProtocolMethodName => "exchange.declare";
        public override bool HasContent => false;

        public override void ReadArgumentsFrom(ref Client.Impl.MethodArgumentReader reader)
        {
            _reserved1 = reader.ReadShort();
            _exchange = reader.ReadShortstr();
            _type = reader.ReadShortstr();
            _passive = reader.ReadBit();
            _durable = reader.ReadBit();
            _autoDelete = reader.ReadBit();
            _internal = reader.ReadBit();
            _nowait = reader.ReadBit();
            _arguments = reader.ReadTable();
        }

        public override void WriteArgumentsTo(ref Client.Impl.MethodArgumentWriter writer)
        {
            writer.WriteShort(_reserved1);
            writer.WriteShortstr(_exchange);
            writer.WriteShortstr(_type);
            writer.WriteBit(_passive);
            writer.WriteBit(_durable);
            writer.WriteBit(_autoDelete);
            writer.WriteBit(_internal);
            writer.WriteBit(_nowait);
            writer.EndBits();
            writer.WriteTable(_arguments);
        }

        public override int GetRequiredBufferSize()
        {
            int bufferSize = 5; // bytes for _reserved1, length of _exchange, length of _type, bit fields
            bufferSize += Encoding.UTF8.GetByteCount(_exchange); // _exchange in bytes
            bufferSize += Encoding.UTF8.GetByteCount(_type); // _type in bytes
            bufferSize += WireFormatting.GetTableByteCount(_arguments); // _arguments in bytes
            return bufferSize;
        }

        public override void AppendArgumentDebugStringTo(StringBuilder sb)
        {
            sb.Append('(');
            sb.Append(_reserved1).Append(',');
            sb.Append(_exchange).Append(',');
            sb.Append(_type).Append(',');
            sb.Append(_passive).Append(',');
            sb.Append(_durable).Append(',');
            sb.Append(_autoDelete).Append(',');
            sb.Append(_internal).Append(',');
            sb.Append(_nowait).Append(',');
            sb.Append(_arguments);
            sb.Append(')');
        }
    }
}
