name: rabbitmq-dotnet-client-oauth2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-test:
    strategy:
      matrix:
        oauth2-provider: [ uaa, keycloak ]
    name: oauth2-${{ matrix.oauth2-provider }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: true
      - uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
        with:
          dotnet-version: 8.x
      - uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
        with:
          path: |
            ~/.nuget/packages
            ~/.local/share/NuGet/v3-cache
          key: ${{ runner.os }}-v0-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-v0-nuget-
      - run: ${{ github.workspace }}/.ci/oauth2/setup.sh ${{ matrix.oauth2-provider }}
      - run: ${{ github.workspace }}/.ci/oauth2/test.sh ${{ matrix.oauth2-provider }}
